### ISSUE TITLE
Unable to build iOS 64-bit app when using MoPub bindings?

### ISSUE THREAD

**Issue by jsras** [BlueRiverInteractive/robovm-ios-bindings#154]
I am currently experiencing some issues when building for 64-bit with the MoPub bindings.
The IPA gets created fine enough, but the 64-bit slice won't work, since the MoPub bindings aren't built for 64-bit. Furthermore the app continually crashes when run on 64-bit simulator.
I've tried using current roboVM snapshot, beta 1, 2 and  3. Also tried MoPub bindings snapshot, beta 1,2 and 3, but to no avail.

Warning when building: warning: ignoring file /Users/jsr/.robovm/cache/ios/x86_64/release/Users/jsr/Development/Mojo Studios/Rainbow Run/ios/libs/mopub-1.0.0-beta-03.jar.extracted/META-INF/robovm/ios/libs/libmopub.a, missing required architecture x86_64 in file /Users/jsr/.robovm/cache/ios/x86_64/release/Users/jsr/Development/Mojo Studios/Rainbow Run/ios/libs/mopub-1.0.0-beta-03.jar.extracted/META-INF/robovm/ios/libs/libmopub.a (3 slices)

Error:  
 java.lang.ExceptionInInitializerError

	at com.mojo.rainbowrun.ActionResolverIOS.<init>(ActionResolverIOS.java)
	at com.mojo.rainbowrun.IOSLauncher.createApplication(IOSLauncher.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(IOSApplication.java)
	at com.mojo.rainbowrun.IOSLauncher.didFinishLaunching(IOSLauncher.java)
	at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.mojo.rainbowrun.IOSLauncher.main(IOSLauncher.java)
Caused by: org.robovm.objc.ObjCClassNotFoundException: MPInterstitialAdController
	at org.robovm.objc.ObjCClass.getByType(ObjCClass.java)
	at org.robovm.bindings.mopub.MPInterstitialAdController.<clinit>(MPInterstitialAdController.java)
	... 8 more

I have tried a lot of different solutions and I feel like I am going crazy or code-blind.

**Comment by m8tto** [comment]
Same here.
Looks like we need beta 4 binding , but no info when it will be released.
Please tell us if it 'll take some time (more then a week) 'cause we're ready to publish our new game and need to decide, to wait new binding or to use something different for now.

Thank you for your great job.

**Comment by jsras** [comment]
We ended up using admob binding instead of the mopub one, since there wasn't really any solution to this issue yet, and no words on when it might be solved. But the admob binding works great with iOS 64-bit.

**Comment by m8tto** [comment]
Yeah. Thinking of that too. Have posted reply in google groups. If release will be soon than I'll use it. In other way I'll use admit also.

**Comment by m8tto** [comment]
@jsras can you contact me about how you've implemented admob binding?
I have a problem with banners on real devices (banner shows but game stops at this moment and i can do nothing).
My mail: rating7.com@gmail.com

**Comment by jcassani** [comment]
Any progress with this issue? It would be nice to be able to use the mopub binding again

**Comment by krasanen** [comment]
Still no 64bit mopub? Can we build it ourselves?

**Comment by BlueRiverInteractive** [comment]
MoPub is on the todo list for new RoboPods: https://github.com/robovm/robovm-robopods/issues/17
It will feature all RoboVM compatible ad networks and also work for 64-bit. 
I can't give an ETA yet when it will be finished. GPGS, Parse and AdMob have higher priority at this time.

**Comment by BlueRiverInteractive** [comment]
Whops, wrong link: https://github.com/robovm/robovm-robopods/issues/9
