### ISSUE TITLE
Vungle sample not working

### ISSUE THREAD

**Issue by TheAndroidMachine** [BlueRiverInteractive/robovm-ios-bindings#170]
Currently the Vungle sample is not working.

To reproduce it:
1- download the samples
2- import the projects into eclipse
3- run the Vungle sample on the simulator

The exception:
java.lang.ExceptionInInitializerError
	at org.robovm.bindings.vungle.sample.Sample.didFinishLaunching(Sample.java)
	at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$applicationDidFinishLaunching$(Unknown Source)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at org.robovm.bindings.vungle.sample.Sample.main(Sample.java)
Caused by: org.robovm.objc.ObjCClassNotFoundException: VGVunglePub
	at org.robovm.objc.ObjCClass.getByType(ObjCClass.java)
	at org.robovm.bindings.vungle.VGVunglePub.<clinit>(VGVunglePub.java)
	... 5 more

I have tested the admob and the facebook samples and I did not have any problems.

**Comment by xirtam-ch** [comment]
Same issue here.
