### ISSUE TITLE
Chartboost.start(...) -> Exception

### ISSUE THREAD

**Issue by wsrdzg** [BlueRiverInteractive/robovm-ios-bindings#180]
I use the Chartboost extension in my iOS libGDX project. But if I call [i]Chartboost.start(...)[/i] I always get the following exception.
```java.lang.ClassCastException: com.example.game.IOSLauncher$1 cannot be cast to org.robovm.objc.ObjCObject
	at org.robovm.objc.ObjCObject$Marshaler.protocolToNative(ObjCObject.java)
	at org.robovm.bindings.chartboost.Chartboost.$m$startWithAppId$appSignature$delegate$(Native Method)
	at org.robovm.bindings.chartboost.Chartboost.start(Chartboost.java)
	at com.example.game.IOSLauncher.didFinishLaunching(IOSLauncher.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.$cb$application$didFinishLaunchingWithOptions$(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.example.game.IOSLauncher.main(IOSLauncher.java)```

**Comment by BlueRiverInteractive** [comment]
The Chartboost binding is subject to be deleted. Please use the new iOS RoboPod for Chartboost: https://github.com/robovm/robovm-robopods
